/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package az.kon.academy.catalog.avro.model.product.stock;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class ProductStockDecreasedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7917933673808963845L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductStockDecreasedAvroModel\",\"namespace\":\"az.kon.academy.catalog.avro.model.product.stock\",\"fields\":[{\"name\":\"newQuantity\",\"type\":\"int\"},{\"name\":\"removedQuantity\",\"type\":\"int\"},{\"name\":\"aggregateId\",\"type\":\"string\"},{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"version\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ProductStockDecreasedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductStockDecreasedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductStockDecreasedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductStockDecreasedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductStockDecreasedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductStockDecreasedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductStockDecreasedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductStockDecreasedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductStockDecreasedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int newQuantity;
  private int removedQuantity;
  private java.lang.CharSequence aggregateId;
  private java.util.UUID eventId;
  private java.time.Instant timestamp;
  private int version;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductStockDecreasedAvroModel() {}

  /**
   * All-args constructor.
   * @param newQuantity The new value for newQuantity
   * @param removedQuantity The new value for removedQuantity
   * @param aggregateId The new value for aggregateId
   * @param eventId The new value for eventId
   * @param timestamp The new value for timestamp
   * @param version The new value for version
   */
  public ProductStockDecreasedAvroModel(java.lang.Integer newQuantity, java.lang.Integer removedQuantity, java.lang.CharSequence aggregateId, java.util.UUID eventId, java.time.Instant timestamp, java.lang.Integer version) {
    this.newQuantity = newQuantity;
    this.removedQuantity = removedQuantity;
    this.aggregateId = aggregateId;
    this.eventId = eventId;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.version = version;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return newQuantity;
    case 1: return removedQuantity;
    case 2: return aggregateId;
    case 3: return eventId;
    case 4: return timestamp;
    case 5: return version;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: newQuantity = (java.lang.Integer)value$; break;
    case 1: removedQuantity = (java.lang.Integer)value$; break;
    case 2: aggregateId = (java.lang.CharSequence)value$; break;
    case 3: eventId = (java.util.UUID)value$; break;
    case 4: timestamp = (java.time.Instant)value$; break;
    case 5: version = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'newQuantity' field.
   * @return The value of the 'newQuantity' field.
   */
  public int getNewQuantity() {
    return newQuantity;
  }

  /**
   * Gets the value of the 'newQuantity' field as an Optional&lt;java.lang.Integer&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
   */
  public Optional<java.lang.Integer> getOptionalNewQuantity() {
    return Optional.<java.lang.Integer>ofNullable(newQuantity);
  }

  /**
   * Sets the value of the 'newQuantity' field.
   * @param value the value to set.
   */
  public void setNewQuantity(int value) {
    this.newQuantity = value;
  }

  /**
   * Gets the value of the 'removedQuantity' field.
   * @return The value of the 'removedQuantity' field.
   */
  public int getRemovedQuantity() {
    return removedQuantity;
  }

  /**
   * Gets the value of the 'removedQuantity' field as an Optional&lt;java.lang.Integer&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
   */
  public Optional<java.lang.Integer> getOptionalRemovedQuantity() {
    return Optional.<java.lang.Integer>ofNullable(removedQuantity);
  }

  /**
   * Sets the value of the 'removedQuantity' field.
   * @param value the value to set.
   */
  public void setRemovedQuantity(int value) {
    this.removedQuantity = value;
  }

  /**
   * Gets the value of the 'aggregateId' field.
   * @return The value of the 'aggregateId' field.
   */
  public java.lang.CharSequence getAggregateId() {
    return aggregateId;
  }

  /**
   * Gets the value of the 'aggregateId' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalAggregateId() {
    return Optional.<java.lang.CharSequence>ofNullable(aggregateId);
  }

  /**
   * Sets the value of the 'aggregateId' field.
   * @param value the value to set.
   */
  public void setAggregateId(java.lang.CharSequence value) {
    this.aggregateId = value;
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.util.UUID getEventId() {
    return eventId;
  }

  /**
   * Gets the value of the 'eventId' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalEventId() {
    return Optional.<java.util.UUID>ofNullable(eventId);
  }

  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.util.UUID value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }

  /**
   * Gets the value of the 'timestamp' field as an Optional&lt;java.time.Instant&gt;.
   * @return The value wrapped in an Optional&lt;java.time.Instant&gt;.
   */
  public Optional<java.time.Instant> getOptionalTimestamp() {
    return Optional.<java.time.Instant>ofNullable(timestamp);
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public int getVersion() {
    return version;
  }

  /**
   * Gets the value of the 'version' field as an Optional&lt;java.lang.Integer&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
   */
  public Optional<java.lang.Integer> getOptionalVersion() {
    return Optional.<java.lang.Integer>ofNullable(version);
  }

  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(int value) {
    this.version = value;
  }

  /**
   * Creates a new ProductStockDecreasedAvroModel RecordBuilder.
   * @return A new ProductStockDecreasedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder newBuilder() {
    return new az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder();
  }

  /**
   * Creates a new ProductStockDecreasedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductStockDecreasedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new ProductStockDecreasedAvroModel RecordBuilder by copying an existing ProductStockDecreasedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new ProductStockDecreasedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductStockDecreasedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductStockDecreasedAvroModel>
    implements org.apache.avro.data.RecordBuilder<ProductStockDecreasedAvroModel> {

    private int newQuantity;
    private int removedQuantity;
    private java.lang.CharSequence aggregateId;
    private java.util.UUID eventId;
    private java.time.Instant timestamp;
    private int version;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.newQuantity)) {
        this.newQuantity = data().deepCopy(fields()[0].schema(), other.newQuantity);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.removedQuantity)) {
        this.removedQuantity = data().deepCopy(fields()[1].schema(), other.removedQuantity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[2].schema(), other.aggregateId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.eventId)) {
        this.eventId = data().deepCopy(fields()[3].schema(), other.eventId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.version)) {
        this.version = data().deepCopy(fields()[5].schema(), other.version);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductStockDecreasedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.newQuantity)) {
        this.newQuantity = data().deepCopy(fields()[0].schema(), other.newQuantity);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.removedQuantity)) {
        this.removedQuantity = data().deepCopy(fields()[1].schema(), other.removedQuantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[2].schema(), other.aggregateId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.eventId)) {
        this.eventId = data().deepCopy(fields()[3].schema(), other.eventId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.version)) {
        this.version = data().deepCopy(fields()[5].schema(), other.version);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'newQuantity' field.
      * @return The value.
      */
    public int getNewQuantity() {
      return newQuantity;
    }

    /**
      * Gets the value of the 'newQuantity' field as an Optional&lt;java.lang.Integer&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
      */
    public Optional<java.lang.Integer> getOptionalNewQuantity() {
      return Optional.<java.lang.Integer>ofNullable(newQuantity);
    }

    /**
      * Sets the value of the 'newQuantity' field.
      * @param value The value of 'newQuantity'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder setNewQuantity(int value) {
      validate(fields()[0], value);
      this.newQuantity = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'newQuantity' field has been set.
      * @return True if the 'newQuantity' field has been set, false otherwise.
      */
    public boolean hasNewQuantity() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'newQuantity' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder clearNewQuantity() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'removedQuantity' field.
      * @return The value.
      */
    public int getRemovedQuantity() {
      return removedQuantity;
    }

    /**
      * Gets the value of the 'removedQuantity' field as an Optional&lt;java.lang.Integer&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
      */
    public Optional<java.lang.Integer> getOptionalRemovedQuantity() {
      return Optional.<java.lang.Integer>ofNullable(removedQuantity);
    }

    /**
      * Sets the value of the 'removedQuantity' field.
      * @param value The value of 'removedQuantity'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder setRemovedQuantity(int value) {
      validate(fields()[1], value);
      this.removedQuantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'removedQuantity' field has been set.
      * @return True if the 'removedQuantity' field has been set, false otherwise.
      */
    public boolean hasRemovedQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'removedQuantity' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder clearRemovedQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'aggregateId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAggregateId() {
      return aggregateId;
    }

    /**
      * Gets the value of the 'aggregateId' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalAggregateId() {
      return Optional.<java.lang.CharSequence>ofNullable(aggregateId);
    }

    /**
      * Sets the value of the 'aggregateId' field.
      * @param value The value of 'aggregateId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder setAggregateId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.aggregateId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'aggregateId' field has been set.
      * @return True if the 'aggregateId' field has been set, false otherwise.
      */
    public boolean hasAggregateId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'aggregateId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder clearAggregateId() {
      aggregateId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.util.UUID getEventId() {
      return eventId;
    }

    /**
      * Gets the value of the 'eventId' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalEventId() {
      return Optional.<java.util.UUID>ofNullable(eventId);
    }

    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder setEventId(java.util.UUID value) {
      validate(fields()[3], value);
      this.eventId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }

    /**
      * Gets the value of the 'timestamp' field as an Optional&lt;java.time.Instant&gt;.
      * @return The value wrapped in an Optional&lt;java.time.Instant&gt;.
      */
    public Optional<java.time.Instant> getOptionalTimestamp() {
      return Optional.<java.time.Instant>ofNullable(timestamp);
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[4], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public int getVersion() {
      return version;
    }

    /**
      * Gets the value of the 'version' field as an Optional&lt;java.lang.Integer&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
      */
    public Optional<java.lang.Integer> getOptionalVersion() {
      return Optional.<java.lang.Integer>ofNullable(version);
    }

    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder setVersion(int value) {
      validate(fields()[5], value);
      this.version = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.stock.ProductStockDecreasedAvroModel.Builder clearVersion() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductStockDecreasedAvroModel build() {
      try {
        ProductStockDecreasedAvroModel record = new ProductStockDecreasedAvroModel();
        record.newQuantity = fieldSetFlags()[0] ? this.newQuantity : (java.lang.Integer) defaultValue(fields()[0]);
        record.removedQuantity = fieldSetFlags()[1] ? this.removedQuantity : (java.lang.Integer) defaultValue(fields()[1]);
        record.aggregateId = fieldSetFlags()[2] ? this.aggregateId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.eventId = fieldSetFlags()[3] ? this.eventId : (java.util.UUID) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.time.Instant) defaultValue(fields()[4]);
        record.version = fieldSetFlags()[5] ? this.version : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductStockDecreasedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductStockDecreasedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductStockDecreasedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<ProductStockDecreasedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }


  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + Integer.hashCode(newQuantity);
    result = 31 * result + Integer.hashCode(removedQuantity);
    result = 31 * result + (aggregateId == null ? 0 : aggregateId.hashCode());
    result = 31 * result + (eventId == null ? 0 : eventId.hashCode());
    result = 31 * result + (timestamp == null ? 0 : timestamp.hashCode());
    result = 31 * result + Integer.hashCode(version);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ProductStockDecreasedAvroModel)) {
      return false;
    }
    ProductStockDecreasedAvroModel other = (ProductStockDecreasedAvroModel) o;
    if (this.newQuantity != other.newQuantity) {
      return false;
    }
    if (this.removedQuantity != other.removedQuantity) {
      return false;
    }
    if (Utf8.compareSequences(this.aggregateId, other.aggregateId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.eventId, other.eventId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.timestamp, other.timestamp)) {
      return false;
    }
    if (this.version != other.version) {
      return false;
    }
    return true;
  }
}










