{
  "type": "record",
  "name": "ProductMovedToDraftAvroModel",
  "namespace": "az.kon.academy.catalog.avro.model.product",
  "fields": [
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "aggregateId",
      "type": "string"
    },
    {
      "name": "eventId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "version",
      "type": "int"
    }
  ]
}