<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>az.kon.academy</groupId>
        <artifactId>store-engine</artifactId>
        <version>1.0.0-ALPHA</version>
    </parent>

    <artifactId>example</artifactId>

    <dependencies>
        <dependency>
            <groupId>az.kon.academy</groupId>
            <artifactId>store-engine-lib-parent</artifactId>
            <version>1.0.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>


        <dependency>
            <groupId>az.kon.academy.event</groupId>
            <artifactId>se-event-dispatcher-spring-boot-starter</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>az.kon.academy.event</groupId>
            <artifactId>se-event-dispatcher-internal</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>az.kon.academy.event</groupId>
            <artifactId>se-event-dispatcher-kafka</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>az.kon.academy.event</groupId>
            <artifactId>se-event-handler-spring-boot-starter</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- Spring Boot Starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <!-- Spring Boot Test Starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
</project>