/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package az.kon.academy.catalog.avro.model.brand;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class BrandAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8235237771701224617L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BrandAvroModel\",\"namespace\":\"az.kon.academy.catalog.avro.model.brand\",\"fields\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BrandAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BrandAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BrandAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BrandAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BrandAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BrandAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BrandAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BrandAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BrandAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }


  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Creates a new BrandAvroModel RecordBuilder.
   * @return A new BrandAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.brand.BrandAvroModel.Builder newBuilder() {
    return new az.kon.academy.catalog.avro.model.brand.BrandAvroModel.Builder();
  }

  /**
   * Creates a new BrandAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BrandAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.brand.BrandAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.brand.BrandAvroModel.Builder other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.brand.BrandAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.brand.BrandAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new BrandAvroModel RecordBuilder by copying an existing BrandAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new BrandAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.brand.BrandAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.brand.BrandAvroModel other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.brand.BrandAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.brand.BrandAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for BrandAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BrandAvroModel>
    implements org.apache.avro.data.RecordBuilder<BrandAvroModel> {


    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.brand.BrandAvroModel.Builder other) {
      super(other);
    }

    /**
     * Creates a Builder by copying an existing BrandAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.brand.BrandAvroModel other) {
      super(SCHEMA$, MODEL$);
    }

    @Override
    @SuppressWarnings("unchecked")
    public BrandAvroModel build() {
      try {
        BrandAvroModel record = new BrandAvroModel();
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BrandAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<BrandAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BrandAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<BrandAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
    } else {
      for (int i = 0; i < 0; i++) {
        switch (fieldOrder[i].pos()) {
        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof BrandAvroModel)) {
      return false;
    }
    BrandAvroModel other = (BrandAvroModel) o;
    return true;
  }
}










