{
  "type" : "record",
  "name" : "BrandToGlobalChangedAvroModel",
  "namespace" : "az.kon.academy.catalog.avro.model.brand",
  "fields" : [ {
    "name" : "isGLobal",
    "type" : "boolean"
  }, {
    "name" : "aggregateId",
    "type" : "string"
  }, {
    "name" : "eventId",
    "type" : {
      "type" : "string",
      "logicalType" : "uuid"
    }
  }, {
    "name" : "timestamp",
    "type" : {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    }
  }, {
    "name" : "version",
    "type" : "int"
  } ]
}