/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package az.kon.academy.catalog.avro.model.product;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class ProductVariantAddedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6759748047545846695L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductVariantAddedAvroModel\",\"namespace\":\"az.kon.academy.catalog.avro.model.product\",\"fields\":[{\"name\":\"variantId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"variantKeyIds\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"java-class\":\"java.util.List\"}},{\"name\":\"variantValueIds\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"java-class\":\"java.util.List\"}},{\"name\":\"aggregateId\",\"type\":\"string\"},{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"version\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ProductVariantAddedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductVariantAddedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductVariantAddedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductVariantAddedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductVariantAddedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductVariantAddedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductVariantAddedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductVariantAddedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductVariantAddedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID variantId;
  private java.util.List<java.util.UUID> variantKeyIds;
  private java.util.List<java.util.UUID> variantValueIds;
  private java.lang.CharSequence aggregateId;
  private java.util.UUID eventId;
  private java.time.Instant timestamp;
  private int version;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductVariantAddedAvroModel() {}

  /**
   * All-args constructor.
   * @param variantId The new value for variantId
   * @param variantKeyIds The new value for variantKeyIds
   * @param variantValueIds The new value for variantValueIds
   * @param aggregateId The new value for aggregateId
   * @param eventId The new value for eventId
   * @param timestamp The new value for timestamp
   * @param version The new value for version
   */
  public ProductVariantAddedAvroModel(java.util.UUID variantId, java.util.List<java.util.UUID> variantKeyIds, java.util.List<java.util.UUID> variantValueIds, java.lang.CharSequence aggregateId, java.util.UUID eventId, java.time.Instant timestamp, java.lang.Integer version) {
    this.variantId = variantId;
    this.variantKeyIds = variantKeyIds;
    this.variantValueIds = variantValueIds;
    this.aggregateId = aggregateId;
    this.eventId = eventId;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.version = version;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return variantId;
    case 1: return variantKeyIds;
    case 2: return variantValueIds;
    case 3: return aggregateId;
    case 4: return eventId;
    case 5: return timestamp;
    case 6: return version;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: variantId = (java.util.UUID)value$; break;
    case 1: variantKeyIds = (java.util.List<java.util.UUID>)value$; break;
    case 2: variantValueIds = (java.util.List<java.util.UUID>)value$; break;
    case 3: aggregateId = (java.lang.CharSequence)value$; break;
    case 4: eventId = (java.util.UUID)value$; break;
    case 5: timestamp = (java.time.Instant)value$; break;
    case 6: version = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'variantId' field.
   * @return The value of the 'variantId' field.
   */
  public java.util.UUID getVariantId() {
    return variantId;
  }

  /**
   * Gets the value of the 'variantId' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalVariantId() {
    return Optional.<java.util.UUID>ofNullable(variantId);
  }

  /**
   * Sets the value of the 'variantId' field.
   * @param value the value to set.
   */
  public void setVariantId(java.util.UUID value) {
    this.variantId = value;
  }

  /**
   * Gets the value of the 'variantKeyIds' field.
   * @return The value of the 'variantKeyIds' field.
   */
  public java.util.List<java.util.UUID> getVariantKeyIds() {
    return variantKeyIds;
  }

  /**
   * Gets the value of the 'variantKeyIds' field as an Optional&lt;java.util.List&lt;java.util.UUID&gt;&gt;.
   * @return The value wrapped in an Optional&lt;java.util.List&lt;java.util.UUID&gt;&gt;.
   */
  public Optional<java.util.List<java.util.UUID>> getOptionalVariantKeyIds() {
    return Optional.<java.util.List<java.util.UUID>>ofNullable(variantKeyIds);
  }

  /**
   * Sets the value of the 'variantKeyIds' field.
   * @param value the value to set.
   */
  public void setVariantKeyIds(java.util.List<java.util.UUID> value) {
    this.variantKeyIds = value;
  }

  /**
   * Gets the value of the 'variantValueIds' field.
   * @return The value of the 'variantValueIds' field.
   */
  public java.util.List<java.util.UUID> getVariantValueIds() {
    return variantValueIds;
  }

  /**
   * Gets the value of the 'variantValueIds' field as an Optional&lt;java.util.List&lt;java.util.UUID&gt;&gt;.
   * @return The value wrapped in an Optional&lt;java.util.List&lt;java.util.UUID&gt;&gt;.
   */
  public Optional<java.util.List<java.util.UUID>> getOptionalVariantValueIds() {
    return Optional.<java.util.List<java.util.UUID>>ofNullable(variantValueIds);
  }

  /**
   * Sets the value of the 'variantValueIds' field.
   * @param value the value to set.
   */
  public void setVariantValueIds(java.util.List<java.util.UUID> value) {
    this.variantValueIds = value;
  }

  /**
   * Gets the value of the 'aggregateId' field.
   * @return The value of the 'aggregateId' field.
   */
  public java.lang.CharSequence getAggregateId() {
    return aggregateId;
  }

  /**
   * Gets the value of the 'aggregateId' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalAggregateId() {
    return Optional.<java.lang.CharSequence>ofNullable(aggregateId);
  }

  /**
   * Sets the value of the 'aggregateId' field.
   * @param value the value to set.
   */
  public void setAggregateId(java.lang.CharSequence value) {
    this.aggregateId = value;
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.util.UUID getEventId() {
    return eventId;
  }

  /**
   * Gets the value of the 'eventId' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalEventId() {
    return Optional.<java.util.UUID>ofNullable(eventId);
  }

  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.util.UUID value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }

  /**
   * Gets the value of the 'timestamp' field as an Optional&lt;java.time.Instant&gt;.
   * @return The value wrapped in an Optional&lt;java.time.Instant&gt;.
   */
  public Optional<java.time.Instant> getOptionalTimestamp() {
    return Optional.<java.time.Instant>ofNullable(timestamp);
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public int getVersion() {
    return version;
  }

  /**
   * Gets the value of the 'version' field as an Optional&lt;java.lang.Integer&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
   */
  public Optional<java.lang.Integer> getOptionalVersion() {
    return Optional.<java.lang.Integer>ofNullable(version);
  }

  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(int value) {
    this.version = value;
  }

  /**
   * Creates a new ProductVariantAddedAvroModel RecordBuilder.
   * @return A new ProductVariantAddedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder newBuilder() {
    return new az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder();
  }

  /**
   * Creates a new ProductVariantAddedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductVariantAddedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new ProductVariantAddedAvroModel RecordBuilder by copying an existing ProductVariantAddedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new ProductVariantAddedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductVariantAddedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductVariantAddedAvroModel>
    implements org.apache.avro.data.RecordBuilder<ProductVariantAddedAvroModel> {

    private java.util.UUID variantId;
    private java.util.List<java.util.UUID> variantKeyIds;
    private java.util.List<java.util.UUID> variantValueIds;
    private java.lang.CharSequence aggregateId;
    private java.util.UUID eventId;
    private java.time.Instant timestamp;
    private int version;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.variantId)) {
        this.variantId = data().deepCopy(fields()[0].schema(), other.variantId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.variantKeyIds)) {
        this.variantKeyIds = data().deepCopy(fields()[1].schema(), other.variantKeyIds);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.variantValueIds)) {
        this.variantValueIds = data().deepCopy(fields()[2].schema(), other.variantValueIds);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[3].schema(), other.aggregateId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.eventId)) {
        this.eventId = data().deepCopy(fields()[4].schema(), other.eventId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.version)) {
        this.version = data().deepCopy(fields()[6].schema(), other.version);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductVariantAddedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.variantId)) {
        this.variantId = data().deepCopy(fields()[0].schema(), other.variantId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.variantKeyIds)) {
        this.variantKeyIds = data().deepCopy(fields()[1].schema(), other.variantKeyIds);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.variantValueIds)) {
        this.variantValueIds = data().deepCopy(fields()[2].schema(), other.variantValueIds);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[3].schema(), other.aggregateId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.eventId)) {
        this.eventId = data().deepCopy(fields()[4].schema(), other.eventId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.version)) {
        this.version = data().deepCopy(fields()[6].schema(), other.version);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'variantId' field.
      * @return The value.
      */
    public java.util.UUID getVariantId() {
      return variantId;
    }

    /**
      * Gets the value of the 'variantId' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalVariantId() {
      return Optional.<java.util.UUID>ofNullable(variantId);
    }

    /**
      * Sets the value of the 'variantId' field.
      * @param value The value of 'variantId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder setVariantId(java.util.UUID value) {
      validate(fields()[0], value);
      this.variantId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'variantId' field has been set.
      * @return True if the 'variantId' field has been set, false otherwise.
      */
    public boolean hasVariantId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'variantId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder clearVariantId() {
      variantId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'variantKeyIds' field.
      * @return The value.
      */
    public java.util.List<java.util.UUID> getVariantKeyIds() {
      return variantKeyIds;
    }

    /**
      * Gets the value of the 'variantKeyIds' field as an Optional&lt;java.util.List&lt;java.util.UUID&gt;&gt;.
      * @return The value wrapped in an Optional&lt;java.util.List&lt;java.util.UUID&gt;&gt;.
      */
    public Optional<java.util.List<java.util.UUID>> getOptionalVariantKeyIds() {
      return Optional.<java.util.List<java.util.UUID>>ofNullable(variantKeyIds);
    }

    /**
      * Sets the value of the 'variantKeyIds' field.
      * @param value The value of 'variantKeyIds'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder setVariantKeyIds(java.util.List<java.util.UUID> value) {
      validate(fields()[1], value);
      this.variantKeyIds = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'variantKeyIds' field has been set.
      * @return True if the 'variantKeyIds' field has been set, false otherwise.
      */
    public boolean hasVariantKeyIds() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'variantKeyIds' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder clearVariantKeyIds() {
      variantKeyIds = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'variantValueIds' field.
      * @return The value.
      */
    public java.util.List<java.util.UUID> getVariantValueIds() {
      return variantValueIds;
    }

    /**
      * Gets the value of the 'variantValueIds' field as an Optional&lt;java.util.List&lt;java.util.UUID&gt;&gt;.
      * @return The value wrapped in an Optional&lt;java.util.List&lt;java.util.UUID&gt;&gt;.
      */
    public Optional<java.util.List<java.util.UUID>> getOptionalVariantValueIds() {
      return Optional.<java.util.List<java.util.UUID>>ofNullable(variantValueIds);
    }

    /**
      * Sets the value of the 'variantValueIds' field.
      * @param value The value of 'variantValueIds'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder setVariantValueIds(java.util.List<java.util.UUID> value) {
      validate(fields()[2], value);
      this.variantValueIds = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'variantValueIds' field has been set.
      * @return True if the 'variantValueIds' field has been set, false otherwise.
      */
    public boolean hasVariantValueIds() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'variantValueIds' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder clearVariantValueIds() {
      variantValueIds = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'aggregateId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAggregateId() {
      return aggregateId;
    }

    /**
      * Gets the value of the 'aggregateId' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalAggregateId() {
      return Optional.<java.lang.CharSequence>ofNullable(aggregateId);
    }

    /**
      * Sets the value of the 'aggregateId' field.
      * @param value The value of 'aggregateId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder setAggregateId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.aggregateId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'aggregateId' field has been set.
      * @return True if the 'aggregateId' field has been set, false otherwise.
      */
    public boolean hasAggregateId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'aggregateId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder clearAggregateId() {
      aggregateId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.util.UUID getEventId() {
      return eventId;
    }

    /**
      * Gets the value of the 'eventId' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalEventId() {
      return Optional.<java.util.UUID>ofNullable(eventId);
    }

    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder setEventId(java.util.UUID value) {
      validate(fields()[4], value);
      this.eventId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }

    /**
      * Gets the value of the 'timestamp' field as an Optional&lt;java.time.Instant&gt;.
      * @return The value wrapped in an Optional&lt;java.time.Instant&gt;.
      */
    public Optional<java.time.Instant> getOptionalTimestamp() {
      return Optional.<java.time.Instant>ofNullable(timestamp);
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[5], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder clearTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public int getVersion() {
      return version;
    }

    /**
      * Gets the value of the 'version' field as an Optional&lt;java.lang.Integer&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
      */
    public Optional<java.lang.Integer> getOptionalVersion() {
      return Optional.<java.lang.Integer>ofNullable(version);
    }

    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder setVersion(int value) {
      validate(fields()[6], value);
      this.version = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductVariantAddedAvroModel.Builder clearVersion() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductVariantAddedAvroModel build() {
      try {
        ProductVariantAddedAvroModel record = new ProductVariantAddedAvroModel();
        record.variantId = fieldSetFlags()[0] ? this.variantId : (java.util.UUID) defaultValue(fields()[0]);
        record.variantKeyIds = fieldSetFlags()[1] ? this.variantKeyIds : (java.util.List<java.util.UUID>) defaultValue(fields()[1]);
        record.variantValueIds = fieldSetFlags()[2] ? this.variantValueIds : (java.util.List<java.util.UUID>) defaultValue(fields()[2]);
        record.aggregateId = fieldSetFlags()[3] ? this.aggregateId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.eventId = fieldSetFlags()[4] ? this.eventId : (java.util.UUID) defaultValue(fields()[4]);
        record.timestamp = fieldSetFlags()[5] ? this.timestamp : (java.time.Instant) defaultValue(fields()[5]);
        record.version = fieldSetFlags()[6] ? this.version : (java.lang.Integer) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductVariantAddedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductVariantAddedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductVariantAddedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<ProductVariantAddedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }


  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (variantId == null ? 0 : variantId.hashCode());
    result = 31 * result + (variantKeyIds == null ? 0 : variantKeyIds.hashCode());
    result = 31 * result + (variantValueIds == null ? 0 : variantValueIds.hashCode());
    result = 31 * result + (aggregateId == null ? 0 : aggregateId.hashCode());
    result = 31 * result + (eventId == null ? 0 : eventId.hashCode());
    result = 31 * result + (timestamp == null ? 0 : timestamp.hashCode());
    result = 31 * result + Integer.hashCode(version);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ProductVariantAddedAvroModel)) {
      return false;
    }
    ProductVariantAddedAvroModel other = (ProductVariantAddedAvroModel) o;
    if (!java.util.Objects.equals(this.variantId, other.variantId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.variantKeyIds, other.variantKeyIds)) {
      return false;
    }
    if (!java.util.Objects.equals(this.variantValueIds, other.variantValueIds)) {
      return false;
    }
    if (Utf8.compareSequences(this.aggregateId, other.aggregateId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.eventId, other.eventId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.timestamp, other.timestamp)) {
      return false;
    }
    if (this.version != other.version) {
      return false;
    }
    return true;
  }
}










