/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package az.kon.academy.catalog.avro.model.product;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class ProductCreatedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7813464516164423789L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductCreatedAvroModel\",\"namespace\":\"az.kon.academy.catalog.avro.model.product\",\"fields\":[{\"name\":\"barcode\",\"type\":\"string\"},{\"name\":\"brandId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"categoryId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"merchantId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"aggregateId\",\"type\":\"string\"},{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"version\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ProductCreatedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductCreatedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductCreatedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductCreatedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductCreatedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductCreatedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductCreatedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductCreatedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductCreatedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence barcode;
  private java.util.UUID brandId;
  private java.util.UUID categoryId;
  private java.lang.CharSequence description;
  private java.util.UUID merchantId;
  private java.lang.CharSequence name;
  private java.lang.CharSequence status;
  private java.lang.CharSequence aggregateId;
  private java.util.UUID eventId;
  private java.time.Instant timestamp;
  private int version;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductCreatedAvroModel() {}

  /**
   * All-args constructor.
   * @param barcode The new value for barcode
   * @param brandId The new value for brandId
   * @param categoryId The new value for categoryId
   * @param description The new value for description
   * @param merchantId The new value for merchantId
   * @param name The new value for name
   * @param status The new value for status
   * @param aggregateId The new value for aggregateId
   * @param eventId The new value for eventId
   * @param timestamp The new value for timestamp
   * @param version The new value for version
   */
  public ProductCreatedAvroModel(java.lang.CharSequence barcode, java.util.UUID brandId, java.util.UUID categoryId, java.lang.CharSequence description, java.util.UUID merchantId, java.lang.CharSequence name, java.lang.CharSequence status, java.lang.CharSequence aggregateId, java.util.UUID eventId, java.time.Instant timestamp, java.lang.Integer version) {
    this.barcode = barcode;
    this.brandId = brandId;
    this.categoryId = categoryId;
    this.description = description;
    this.merchantId = merchantId;
    this.name = name;
    this.status = status;
    this.aggregateId = aggregateId;
    this.eventId = eventId;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.version = version;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return barcode;
    case 1: return brandId;
    case 2: return categoryId;
    case 3: return description;
    case 4: return merchantId;
    case 5: return name;
    case 6: return status;
    case 7: return aggregateId;
    case 8: return eventId;
    case 9: return timestamp;
    case 10: return version;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: barcode = (java.lang.CharSequence)value$; break;
    case 1: brandId = (java.util.UUID)value$; break;
    case 2: categoryId = (java.util.UUID)value$; break;
    case 3: description = (java.lang.CharSequence)value$; break;
    case 4: merchantId = (java.util.UUID)value$; break;
    case 5: name = (java.lang.CharSequence)value$; break;
    case 6: status = (java.lang.CharSequence)value$; break;
    case 7: aggregateId = (java.lang.CharSequence)value$; break;
    case 8: eventId = (java.util.UUID)value$; break;
    case 9: timestamp = (java.time.Instant)value$; break;
    case 10: version = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'barcode' field.
   * @return The value of the 'barcode' field.
   */
  public java.lang.CharSequence getBarcode() {
    return barcode;
  }

  /**
   * Gets the value of the 'barcode' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalBarcode() {
    return Optional.<java.lang.CharSequence>ofNullable(barcode);
  }

  /**
   * Sets the value of the 'barcode' field.
   * @param value the value to set.
   */
  public void setBarcode(java.lang.CharSequence value) {
    this.barcode = value;
  }

  /**
   * Gets the value of the 'brandId' field.
   * @return The value of the 'brandId' field.
   */
  public java.util.UUID getBrandId() {
    return brandId;
  }

  /**
   * Gets the value of the 'brandId' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalBrandId() {
    return Optional.<java.util.UUID>ofNullable(brandId);
  }

  /**
   * Sets the value of the 'brandId' field.
   * @param value the value to set.
   */
  public void setBrandId(java.util.UUID value) {
    this.brandId = value;
  }

  /**
   * Gets the value of the 'categoryId' field.
   * @return The value of the 'categoryId' field.
   */
  public java.util.UUID getCategoryId() {
    return categoryId;
  }

  /**
   * Gets the value of the 'categoryId' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalCategoryId() {
    return Optional.<java.util.UUID>ofNullable(categoryId);
  }

  /**
   * Sets the value of the 'categoryId' field.
   * @param value the value to set.
   */
  public void setCategoryId(java.util.UUID value) {
    this.categoryId = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Gets the value of the 'description' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalDescription() {
    return Optional.<java.lang.CharSequence>ofNullable(description);
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'merchantId' field.
   * @return The value of the 'merchantId' field.
   */
  public java.util.UUID getMerchantId() {
    return merchantId;
  }

  /**
   * Gets the value of the 'merchantId' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalMerchantId() {
    return Optional.<java.util.UUID>ofNullable(merchantId);
  }

  /**
   * Sets the value of the 'merchantId' field.
   * @param value the value to set.
   */
  public void setMerchantId(java.util.UUID value) {
    this.merchantId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Gets the value of the 'name' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalName() {
    return Optional.<java.lang.CharSequence>ofNullable(name);
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }

  /**
   * Gets the value of the 'status' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalStatus() {
    return Optional.<java.lang.CharSequence>ofNullable(status);
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'aggregateId' field.
   * @return The value of the 'aggregateId' field.
   */
  public java.lang.CharSequence getAggregateId() {
    return aggregateId;
  }

  /**
   * Gets the value of the 'aggregateId' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalAggregateId() {
    return Optional.<java.lang.CharSequence>ofNullable(aggregateId);
  }

  /**
   * Sets the value of the 'aggregateId' field.
   * @param value the value to set.
   */
  public void setAggregateId(java.lang.CharSequence value) {
    this.aggregateId = value;
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.util.UUID getEventId() {
    return eventId;
  }

  /**
   * Gets the value of the 'eventId' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalEventId() {
    return Optional.<java.util.UUID>ofNullable(eventId);
  }

  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.util.UUID value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }

  /**
   * Gets the value of the 'timestamp' field as an Optional&lt;java.time.Instant&gt;.
   * @return The value wrapped in an Optional&lt;java.time.Instant&gt;.
   */
  public Optional<java.time.Instant> getOptionalTimestamp() {
    return Optional.<java.time.Instant>ofNullable(timestamp);
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public int getVersion() {
    return version;
  }

  /**
   * Gets the value of the 'version' field as an Optional&lt;java.lang.Integer&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
   */
  public Optional<java.lang.Integer> getOptionalVersion() {
    return Optional.<java.lang.Integer>ofNullable(version);
  }

  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(int value) {
    this.version = value;
  }

  /**
   * Creates a new ProductCreatedAvroModel RecordBuilder.
   * @return A new ProductCreatedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder newBuilder() {
    return new az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder();
  }

  /**
   * Creates a new ProductCreatedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductCreatedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new ProductCreatedAvroModel RecordBuilder by copying an existing ProductCreatedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new ProductCreatedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductCreatedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductCreatedAvroModel>
    implements org.apache.avro.data.RecordBuilder<ProductCreatedAvroModel> {

    private java.lang.CharSequence barcode;
    private java.util.UUID brandId;
    private java.util.UUID categoryId;
    private java.lang.CharSequence description;
    private java.util.UUID merchantId;
    private java.lang.CharSequence name;
    private java.lang.CharSequence status;
    private java.lang.CharSequence aggregateId;
    private java.util.UUID eventId;
    private java.time.Instant timestamp;
    private int version;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.barcode)) {
        this.barcode = data().deepCopy(fields()[0].schema(), other.barcode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.brandId)) {
        this.brandId = data().deepCopy(fields()[1].schema(), other.brandId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.categoryId)) {
        this.categoryId = data().deepCopy(fields()[2].schema(), other.categoryId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.merchantId)) {
        this.merchantId = data().deepCopy(fields()[4].schema(), other.merchantId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.name)) {
        this.name = data().deepCopy(fields()[5].schema(), other.name);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.status)) {
        this.status = data().deepCopy(fields()[6].schema(), other.status);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[7].schema(), other.aggregateId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.eventId)) {
        this.eventId = data().deepCopy(fields()[8].schema(), other.eventId);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[9].schema(), other.timestamp);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.version)) {
        this.version = data().deepCopy(fields()[10].schema(), other.version);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductCreatedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.barcode)) {
        this.barcode = data().deepCopy(fields()[0].schema(), other.barcode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.brandId)) {
        this.brandId = data().deepCopy(fields()[1].schema(), other.brandId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.categoryId)) {
        this.categoryId = data().deepCopy(fields()[2].schema(), other.categoryId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.merchantId)) {
        this.merchantId = data().deepCopy(fields()[4].schema(), other.merchantId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.name)) {
        this.name = data().deepCopy(fields()[5].schema(), other.name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.status)) {
        this.status = data().deepCopy(fields()[6].schema(), other.status);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[7].schema(), other.aggregateId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.eventId)) {
        this.eventId = data().deepCopy(fields()[8].schema(), other.eventId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[9].schema(), other.timestamp);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.version)) {
        this.version = data().deepCopy(fields()[10].schema(), other.version);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'barcode' field.
      * @return The value.
      */
    public java.lang.CharSequence getBarcode() {
      return barcode;
    }

    /**
      * Gets the value of the 'barcode' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalBarcode() {
      return Optional.<java.lang.CharSequence>ofNullable(barcode);
    }

    /**
      * Sets the value of the 'barcode' field.
      * @param value The value of 'barcode'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setBarcode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.barcode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'barcode' field has been set.
      * @return True if the 'barcode' field has been set, false otherwise.
      */
    public boolean hasBarcode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'barcode' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearBarcode() {
      barcode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'brandId' field.
      * @return The value.
      */
    public java.util.UUID getBrandId() {
      return brandId;
    }

    /**
      * Gets the value of the 'brandId' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalBrandId() {
      return Optional.<java.util.UUID>ofNullable(brandId);
    }

    /**
      * Sets the value of the 'brandId' field.
      * @param value The value of 'brandId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setBrandId(java.util.UUID value) {
      validate(fields()[1], value);
      this.brandId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'brandId' field has been set.
      * @return True if the 'brandId' field has been set, false otherwise.
      */
    public boolean hasBrandId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'brandId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearBrandId() {
      brandId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'categoryId' field.
      * @return The value.
      */
    public java.util.UUID getCategoryId() {
      return categoryId;
    }

    /**
      * Gets the value of the 'categoryId' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalCategoryId() {
      return Optional.<java.util.UUID>ofNullable(categoryId);
    }

    /**
      * Sets the value of the 'categoryId' field.
      * @param value The value of 'categoryId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setCategoryId(java.util.UUID value) {
      validate(fields()[2], value);
      this.categoryId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryId' field has been set.
      * @return True if the 'categoryId' field has been set, false otherwise.
      */
    public boolean hasCategoryId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'categoryId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearCategoryId() {
      categoryId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }

    /**
      * Gets the value of the 'description' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalDescription() {
      return Optional.<java.lang.CharSequence>ofNullable(description);
    }

    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.description = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearDescription() {
      description = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchantId' field.
      * @return The value.
      */
    public java.util.UUID getMerchantId() {
      return merchantId;
    }

    /**
      * Gets the value of the 'merchantId' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalMerchantId() {
      return Optional.<java.util.UUID>ofNullable(merchantId);
    }

    /**
      * Sets the value of the 'merchantId' field.
      * @param value The value of 'merchantId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setMerchantId(java.util.UUID value) {
      validate(fields()[4], value);
      this.merchantId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'merchantId' field has been set.
      * @return True if the 'merchantId' field has been set, false otherwise.
      */
    public boolean hasMerchantId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'merchantId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearMerchantId() {
      merchantId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Gets the value of the 'name' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalName() {
      return Optional.<java.lang.CharSequence>ofNullable(name);
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.name = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearName() {
      name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }

    /**
      * Gets the value of the 'status' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalStatus() {
      return Optional.<java.lang.CharSequence>ofNullable(status);
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.status = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearStatus() {
      status = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'aggregateId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAggregateId() {
      return aggregateId;
    }

    /**
      * Gets the value of the 'aggregateId' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalAggregateId() {
      return Optional.<java.lang.CharSequence>ofNullable(aggregateId);
    }

    /**
      * Sets the value of the 'aggregateId' field.
      * @param value The value of 'aggregateId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setAggregateId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.aggregateId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'aggregateId' field has been set.
      * @return True if the 'aggregateId' field has been set, false otherwise.
      */
    public boolean hasAggregateId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'aggregateId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearAggregateId() {
      aggregateId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.util.UUID getEventId() {
      return eventId;
    }

    /**
      * Gets the value of the 'eventId' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalEventId() {
      return Optional.<java.util.UUID>ofNullable(eventId);
    }

    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setEventId(java.util.UUID value) {
      validate(fields()[8], value);
      this.eventId = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }

    /**
      * Gets the value of the 'timestamp' field as an Optional&lt;java.time.Instant&gt;.
      * @return The value wrapped in an Optional&lt;java.time.Instant&gt;.
      */
    public Optional<java.time.Instant> getOptionalTimestamp() {
      return Optional.<java.time.Instant>ofNullable(timestamp);
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[9], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearTimestamp() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public int getVersion() {
      return version;
    }

    /**
      * Gets the value of the 'version' field as an Optional&lt;java.lang.Integer&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
      */
    public Optional<java.lang.Integer> getOptionalVersion() {
      return Optional.<java.lang.Integer>ofNullable(version);
    }

    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder setVersion(int value) {
      validate(fields()[10], value);
      this.version = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.product.ProductCreatedAvroModel.Builder clearVersion() {
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductCreatedAvroModel build() {
      try {
        ProductCreatedAvroModel record = new ProductCreatedAvroModel();
        record.barcode = fieldSetFlags()[0] ? this.barcode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.brandId = fieldSetFlags()[1] ? this.brandId : (java.util.UUID) defaultValue(fields()[1]);
        record.categoryId = fieldSetFlags()[2] ? this.categoryId : (java.util.UUID) defaultValue(fields()[2]);
        record.description = fieldSetFlags()[3] ? this.description : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.merchantId = fieldSetFlags()[4] ? this.merchantId : (java.util.UUID) defaultValue(fields()[4]);
        record.name = fieldSetFlags()[5] ? this.name : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.status = fieldSetFlags()[6] ? this.status : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.aggregateId = fieldSetFlags()[7] ? this.aggregateId : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.eventId = fieldSetFlags()[8] ? this.eventId : (java.util.UUID) defaultValue(fields()[8]);
        record.timestamp = fieldSetFlags()[9] ? this.timestamp : (java.time.Instant) defaultValue(fields()[9]);
        record.version = fieldSetFlags()[10] ? this.version : (java.lang.Integer) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductCreatedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductCreatedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductCreatedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<ProductCreatedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }


  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (barcode == null ? 0 : barcode.hashCode());
    result = 31 * result + (brandId == null ? 0 : brandId.hashCode());
    result = 31 * result + (categoryId == null ? 0 : categoryId.hashCode());
    result = 31 * result + (description == null ? 0 : description.hashCode());
    result = 31 * result + (merchantId == null ? 0 : merchantId.hashCode());
    result = 31 * result + (name == null ? 0 : name.hashCode());
    result = 31 * result + (status == null ? 0 : status.hashCode());
    result = 31 * result + (aggregateId == null ? 0 : aggregateId.hashCode());
    result = 31 * result + (eventId == null ? 0 : eventId.hashCode());
    result = 31 * result + (timestamp == null ? 0 : timestamp.hashCode());
    result = 31 * result + Integer.hashCode(version);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ProductCreatedAvroModel)) {
      return false;
    }
    ProductCreatedAvroModel other = (ProductCreatedAvroModel) o;
    if (Utf8.compareSequences(this.barcode, other.barcode) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.brandId, other.brandId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.categoryId, other.categoryId)) {
      return false;
    }
    if (Utf8.compareSequences(this.description, other.description) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.merchantId, other.merchantId)) {
      return false;
    }
    if (Utf8.compareSequences(this.name, other.name) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.status, other.status) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.aggregateId, other.aggregateId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.eventId, other.eventId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.timestamp, other.timestamp)) {
      return false;
    }
    if (this.version != other.version) {
      return false;
    }
    return true;
  }
}










