{
  "type" : "record",
  "name" : "BrandCreatedGlobalAvroModel",
  "namespace" : "az.kon.academy.catalog.avro.model.brand",
  "fields" : [ {
    "name" : "description",
    "type" : "string"
  }, {
    "name" : "isGlobal",
    "type" : "boolean"
  }, {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "owner",
    "type" : {
      "type" : "string",
      "logicalType" : "uuid"
    }
  }, {
    "name" : "path",
    "type" : "string"
  }, {
    "name" : "status",
    "type" : "string"
  }, {
    "name" : "aggregateId",
    "type" : "string"
  }, {
    "name" : "eventId",
    "type" : {
      "type" : "string",
      "logicalType" : "uuid"
    }
  }, {
    "name" : "timestamp",
    "type" : {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    }
  }, {
    "name" : "version",
    "type" : "int"
  } ]
}