{
  "type" : "record",
  "name" : "ProductVariantAddedAvroModel",
  "namespace" : "az.kon.academy.catalog.avro.model.product",
  "fields" : [ {
    "name" : "variantId",
    "type" : {
      "type" : "string",
      "logicalType" : "uuid"
    }
  }, {
    "name" : "variantKeyIds",
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "string",
        "logicalType" : "uuid"
      },
      "java-class" : "java.util.List"
    }
  }, {
    "name" : "variantValueIds",
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "string",
        "logicalType" : "uuid"
      },
      "java-class" : "java.util.List"
    }
  }, {
    "name" : "aggregateId",
    "type" : "string"
  }, {
    "name" : "eventId",
    "type" : {
      "type" : "string",
      "logicalType" : "uuid"
    }
  }, {
    "name" : "timestamp",
    "type" : {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    }
  }, {
    "name" : "version",
    "type" : "int"
  } ]
}