<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>az.kon.academy.catalog</groupId>
        <artifactId>catalog-management</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>catalog-query-service</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>catalog-query-bootstrap</module>
        <module>catagory-query-adapters/catalog-query-inbound-rest</module>
        <module>catagory-query-adapters/catalog-query-inbound-grpc</module>
        <module>catagory-query-adapters/catalog-query-outbound-dao</module>
        <module>catagory-query-adapters/catalog-query-outbound-grpc</module>
    </modules>

</project>