<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>az.kon.academy</groupId>
    <artifactId>store-engine-parent</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>store-engine-parent</name>
    <description>Store Engine Parent</description>
    <developers>
        <developer>
            <id>aqazadeh</id>
            <name>Rovshan Aghayev</name>
            <email>rovsenaqazadeh@gmail.com</email>
        </developer>
    </developers>

    <properties>

        <!-- Revision -->
        <revision>1.0.0-ALPHA</revision>

        <java.version>25</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven-surefire-plugin.version>3.5.5</maven-surefire-plugin.version>
        <maven-compiler.version>3.15.0</maven-compiler.version>
        <maven-flatten-plugin.version>1.7.2</maven-flatten-plugin.version>

        <!-- Spring Boot -->
        <spring-boot.version>4.0.4</spring-boot.version>
        <spring-cloud.version>2025.1.0</spring-cloud.version>

    </properties>

    <repositories>
        <repository>
            <id>confluent</id>
            <url>https://packages.confluent.io/maven/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <!-- Spring Boot BOM -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Spring Cloud BOM -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>${maven-flatten-plugin.version}</version>
                    <configuration>
                        <flattenMode>clean</flattenMode>
                        <pomElements>
                            <parent>keep</parent>
                            <groupId>keep</groupId>
                            <artifactId>keep</artifactId>
                            <version>keep</version>
                            <packaging>keep</packaging>
                            <build>keep</build>
                            <dependencies>keep</dependencies>
                            <repositories>keep</repositories>
                            <dependencyManagement>keep</dependencyManagement>
                            <distributionManagement>keep</distributionManagement>
                            <pluginManagement>keep</pluginManagement>
                            <pluginRepositories>keep</pluginRepositories>
                        </pomElements>
                        <updatePomFile>true</updatePomFile>
                    </configuration>
                    <executions>
                        <execution>
                            <id>flatten</id>
                            <phase>process-resources</phase>
                            <goals>
                                <goal>flatten</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>flatten.clean</id>
                            <phase>clean</phase>
                            <goals>
                                <goal>clean</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler.version}</version>
                    <configuration>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                    <configuration>
                        <forkCount>1</forkCount>
                        <reuseForks>true</reuseForks>
                        <useModulePath>false</useModulePath>
                        <trimStackTrace>false</trimStackTrace>
                        <testFailureIgnore>false</testFailureIgnore>
                        <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                    <configuration>
                        <goal>repackage</goal>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>