/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package az.kon.academy.catalog.avro.model.brand;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class BrandCreatedGlobalAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5826060893967996208L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BrandCreatedGlobalAvroModel\",\"namespace\":\"az.kon.academy.catalog.avro.model.brand\",\"fields\":[{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"isGlobal\",\"type\":\"boolean\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"owner\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"path\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"aggregateId\",\"type\":\"string\"},{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"version\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<BrandCreatedGlobalAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BrandCreatedGlobalAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BrandCreatedGlobalAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BrandCreatedGlobalAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BrandCreatedGlobalAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BrandCreatedGlobalAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BrandCreatedGlobalAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BrandCreatedGlobalAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BrandCreatedGlobalAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence description;
  private boolean isGlobal;
  private java.lang.CharSequence name;
  private java.util.UUID owner;
  private java.lang.CharSequence path;
  private java.lang.CharSequence status;
  private java.lang.CharSequence aggregateId;
  private java.util.UUID eventId;
  private java.time.Instant timestamp;
  private int version;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BrandCreatedGlobalAvroModel() {}

  /**
   * All-args constructor.
   * @param description The new value for description
   * @param isGlobal The new value for isGlobal
   * @param name The new value for name
   * @param owner The new value for owner
   * @param path The new value for path
   * @param status The new value for status
   * @param aggregateId The new value for aggregateId
   * @param eventId The new value for eventId
   * @param timestamp The new value for timestamp
   * @param version The new value for version
   */
  public BrandCreatedGlobalAvroModel(java.lang.CharSequence description, java.lang.Boolean isGlobal, java.lang.CharSequence name, java.util.UUID owner, java.lang.CharSequence path, java.lang.CharSequence status, java.lang.CharSequence aggregateId, java.util.UUID eventId, java.time.Instant timestamp, java.lang.Integer version) {
    this.description = description;
    this.isGlobal = isGlobal;
    this.name = name;
    this.owner = owner;
    this.path = path;
    this.status = status;
    this.aggregateId = aggregateId;
    this.eventId = eventId;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.version = version;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return description;
    case 1: return isGlobal;
    case 2: return name;
    case 3: return owner;
    case 4: return path;
    case 5: return status;
    case 6: return aggregateId;
    case 7: return eventId;
    case 8: return timestamp;
    case 9: return version;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: description = (java.lang.CharSequence)value$; break;
    case 1: isGlobal = (java.lang.Boolean)value$; break;
    case 2: name = (java.lang.CharSequence)value$; break;
    case 3: owner = (java.util.UUID)value$; break;
    case 4: path = (java.lang.CharSequence)value$; break;
    case 5: status = (java.lang.CharSequence)value$; break;
    case 6: aggregateId = (java.lang.CharSequence)value$; break;
    case 7: eventId = (java.util.UUID)value$; break;
    case 8: timestamp = (java.time.Instant)value$; break;
    case 9: version = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Gets the value of the 'description' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalDescription() {
    return Optional.<java.lang.CharSequence>ofNullable(description);
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'isGlobal' field.
   * @return The value of the 'isGlobal' field.
   */
  public boolean getIsGlobal() {
    return isGlobal;
  }

  /**
   * Gets the value of the 'isGlobal' field as an Optional&lt;java.lang.Boolean&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Boolean&gt;.
   */
  public Optional<java.lang.Boolean> getOptionalIsGlobal() {
    return Optional.<java.lang.Boolean>ofNullable(isGlobal);
  }

  /**
   * Sets the value of the 'isGlobal' field.
   * @param value the value to set.
   */
  public void setIsGlobal(boolean value) {
    this.isGlobal = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Gets the value of the 'name' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalName() {
    return Optional.<java.lang.CharSequence>ofNullable(name);
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'owner' field.
   * @return The value of the 'owner' field.
   */
  public java.util.UUID getOwner() {
    return owner;
  }

  /**
   * Gets the value of the 'owner' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalOwner() {
    return Optional.<java.util.UUID>ofNullable(owner);
  }

  /**
   * Sets the value of the 'owner' field.
   * @param value the value to set.
   */
  public void setOwner(java.util.UUID value) {
    this.owner = value;
  }

  /**
   * Gets the value of the 'path' field.
   * @return The value of the 'path' field.
   */
  public java.lang.CharSequence getPath() {
    return path;
  }

  /**
   * Gets the value of the 'path' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalPath() {
    return Optional.<java.lang.CharSequence>ofNullable(path);
  }

  /**
   * Sets the value of the 'path' field.
   * @param value the value to set.
   */
  public void setPath(java.lang.CharSequence value) {
    this.path = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }

  /**
   * Gets the value of the 'status' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalStatus() {
    return Optional.<java.lang.CharSequence>ofNullable(status);
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'aggregateId' field.
   * @return The value of the 'aggregateId' field.
   */
  public java.lang.CharSequence getAggregateId() {
    return aggregateId;
  }

  /**
   * Gets the value of the 'aggregateId' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalAggregateId() {
    return Optional.<java.lang.CharSequence>ofNullable(aggregateId);
  }

  /**
   * Sets the value of the 'aggregateId' field.
   * @param value the value to set.
   */
  public void setAggregateId(java.lang.CharSequence value) {
    this.aggregateId = value;
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.util.UUID getEventId() {
    return eventId;
  }

  /**
   * Gets the value of the 'eventId' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalEventId() {
    return Optional.<java.util.UUID>ofNullable(eventId);
  }

  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.util.UUID value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }

  /**
   * Gets the value of the 'timestamp' field as an Optional&lt;java.time.Instant&gt;.
   * @return The value wrapped in an Optional&lt;java.time.Instant&gt;.
   */
  public Optional<java.time.Instant> getOptionalTimestamp() {
    return Optional.<java.time.Instant>ofNullable(timestamp);
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public int getVersion() {
    return version;
  }

  /**
   * Gets the value of the 'version' field as an Optional&lt;java.lang.Integer&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
   */
  public Optional<java.lang.Integer> getOptionalVersion() {
    return Optional.<java.lang.Integer>ofNullable(version);
  }

  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(int value) {
    this.version = value;
  }

  /**
   * Creates a new BrandCreatedGlobalAvroModel RecordBuilder.
   * @return A new BrandCreatedGlobalAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder newBuilder() {
    return new az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder();
  }

  /**
   * Creates a new BrandCreatedGlobalAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BrandCreatedGlobalAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new BrandCreatedGlobalAvroModel RecordBuilder by copying an existing BrandCreatedGlobalAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new BrandCreatedGlobalAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for BrandCreatedGlobalAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BrandCreatedGlobalAvroModel>
    implements org.apache.avro.data.RecordBuilder<BrandCreatedGlobalAvroModel> {

    private java.lang.CharSequence description;
    private boolean isGlobal;
    private java.lang.CharSequence name;
    private java.util.UUID owner;
    private java.lang.CharSequence path;
    private java.lang.CharSequence status;
    private java.lang.CharSequence aggregateId;
    private java.util.UUID eventId;
    private java.time.Instant timestamp;
    private int version;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.description)) {
        this.description = data().deepCopy(fields()[0].schema(), other.description);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.isGlobal)) {
        this.isGlobal = data().deepCopy(fields()[1].schema(), other.isGlobal);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.owner)) {
        this.owner = data().deepCopy(fields()[3].schema(), other.owner);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.path)) {
        this.path = data().deepCopy(fields()[4].schema(), other.path);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[6].schema(), other.aggregateId);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.eventId)) {
        this.eventId = data().deepCopy(fields()[7].schema(), other.eventId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[8].schema(), other.timestamp);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.version)) {
        this.version = data().deepCopy(fields()[9].schema(), other.version);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing BrandCreatedGlobalAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.description)) {
        this.description = data().deepCopy(fields()[0].schema(), other.description);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.isGlobal)) {
        this.isGlobal = data().deepCopy(fields()[1].schema(), other.isGlobal);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.owner)) {
        this.owner = data().deepCopy(fields()[3].schema(), other.owner);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.path)) {
        this.path = data().deepCopy(fields()[4].schema(), other.path);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[6].schema(), other.aggregateId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.eventId)) {
        this.eventId = data().deepCopy(fields()[7].schema(), other.eventId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[8].schema(), other.timestamp);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.version)) {
        this.version = data().deepCopy(fields()[9].schema(), other.version);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }

    /**
      * Gets the value of the 'description' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalDescription() {
      return Optional.<java.lang.CharSequence>ofNullable(description);
    }

    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.description = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder clearDescription() {
      description = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'isGlobal' field.
      * @return The value.
      */
    public boolean getIsGlobal() {
      return isGlobal;
    }

    /**
      * Gets the value of the 'isGlobal' field as an Optional&lt;java.lang.Boolean&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Boolean&gt;.
      */
    public Optional<java.lang.Boolean> getOptionalIsGlobal() {
      return Optional.<java.lang.Boolean>ofNullable(isGlobal);
    }

    /**
      * Sets the value of the 'isGlobal' field.
      * @param value The value of 'isGlobal'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder setIsGlobal(boolean value) {
      validate(fields()[1], value);
      this.isGlobal = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'isGlobal' field has been set.
      * @return True if the 'isGlobal' field has been set, false otherwise.
      */
    public boolean hasIsGlobal() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'isGlobal' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder clearIsGlobal() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Gets the value of the 'name' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalName() {
      return Optional.<java.lang.CharSequence>ofNullable(name);
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder setName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'owner' field.
      * @return The value.
      */
    public java.util.UUID getOwner() {
      return owner;
    }

    /**
      * Gets the value of the 'owner' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalOwner() {
      return Optional.<java.util.UUID>ofNullable(owner);
    }

    /**
      * Sets the value of the 'owner' field.
      * @param value The value of 'owner'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder setOwner(java.util.UUID value) {
      validate(fields()[3], value);
      this.owner = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'owner' field has been set.
      * @return True if the 'owner' field has been set, false otherwise.
      */
    public boolean hasOwner() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'owner' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder clearOwner() {
      owner = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'path' field.
      * @return The value.
      */
    public java.lang.CharSequence getPath() {
      return path;
    }

    /**
      * Gets the value of the 'path' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalPath() {
      return Optional.<java.lang.CharSequence>ofNullable(path);
    }

    /**
      * Sets the value of the 'path' field.
      * @param value The value of 'path'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder setPath(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.path = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'path' field has been set.
      * @return True if the 'path' field has been set, false otherwise.
      */
    public boolean hasPath() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'path' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder clearPath() {
      path = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }

    /**
      * Gets the value of the 'status' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalStatus() {
      return Optional.<java.lang.CharSequence>ofNullable(status);
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'aggregateId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAggregateId() {
      return aggregateId;
    }

    /**
      * Gets the value of the 'aggregateId' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalAggregateId() {
      return Optional.<java.lang.CharSequence>ofNullable(aggregateId);
    }

    /**
      * Sets the value of the 'aggregateId' field.
      * @param value The value of 'aggregateId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder setAggregateId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.aggregateId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'aggregateId' field has been set.
      * @return True if the 'aggregateId' field has been set, false otherwise.
      */
    public boolean hasAggregateId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'aggregateId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder clearAggregateId() {
      aggregateId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.util.UUID getEventId() {
      return eventId;
    }

    /**
      * Gets the value of the 'eventId' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalEventId() {
      return Optional.<java.util.UUID>ofNullable(eventId);
    }

    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder setEventId(java.util.UUID value) {
      validate(fields()[7], value);
      this.eventId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }

    /**
      * Gets the value of the 'timestamp' field as an Optional&lt;java.time.Instant&gt;.
      * @return The value wrapped in an Optional&lt;java.time.Instant&gt;.
      */
    public Optional<java.time.Instant> getOptionalTimestamp() {
      return Optional.<java.time.Instant>ofNullable(timestamp);
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[8], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder clearTimestamp() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public int getVersion() {
      return version;
    }

    /**
      * Gets the value of the 'version' field as an Optional&lt;java.lang.Integer&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
      */
    public Optional<java.lang.Integer> getOptionalVersion() {
      return Optional.<java.lang.Integer>ofNullable(version);
    }

    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder setVersion(int value) {
      validate(fields()[9], value);
      this.version = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brand.BrandCreatedGlobalAvroModel.Builder clearVersion() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BrandCreatedGlobalAvroModel build() {
      try {
        BrandCreatedGlobalAvroModel record = new BrandCreatedGlobalAvroModel();
        record.description = fieldSetFlags()[0] ? this.description : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.isGlobal = fieldSetFlags()[1] ? this.isGlobal : (java.lang.Boolean) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.owner = fieldSetFlags()[3] ? this.owner : (java.util.UUID) defaultValue(fields()[3]);
        record.path = fieldSetFlags()[4] ? this.path : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.aggregateId = fieldSetFlags()[6] ? this.aggregateId : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.eventId = fieldSetFlags()[7] ? this.eventId : (java.util.UUID) defaultValue(fields()[7]);
        record.timestamp = fieldSetFlags()[8] ? this.timestamp : (java.time.Instant) defaultValue(fields()[8]);
        record.version = fieldSetFlags()[9] ? this.version : (java.lang.Integer) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BrandCreatedGlobalAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<BrandCreatedGlobalAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BrandCreatedGlobalAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<BrandCreatedGlobalAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }


  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (description == null ? 0 : description.hashCode());
    result = 31 * result + Boolean.hashCode(isGlobal);
    result = 31 * result + (name == null ? 0 : name.hashCode());
    result = 31 * result + (owner == null ? 0 : owner.hashCode());
    result = 31 * result + (path == null ? 0 : path.hashCode());
    result = 31 * result + (status == null ? 0 : status.hashCode());
    result = 31 * result + (aggregateId == null ? 0 : aggregateId.hashCode());
    result = 31 * result + (eventId == null ? 0 : eventId.hashCode());
    result = 31 * result + (timestamp == null ? 0 : timestamp.hashCode());
    result = 31 * result + Integer.hashCode(version);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof BrandCreatedGlobalAvroModel)) {
      return false;
    }
    BrandCreatedGlobalAvroModel other = (BrandCreatedGlobalAvroModel) o;
    if (Utf8.compareSequences(this.description, other.description) != 0) {
      return false;
    }
    if (this.isGlobal != other.isGlobal) {
      return false;
    }
    if (Utf8.compareSequences(this.name, other.name) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.owner, other.owner)) {
      return false;
    }
    if (Utf8.compareSequences(this.path, other.path) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.status, other.status) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.aggregateId, other.aggregateId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.eventId, other.eventId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.timestamp, other.timestamp)) {
      return false;
    }
    if (this.version != other.version) {
      return false;
    }
    return true;
  }
}










