/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package az.kon.academy.catalog.avro.model.brandrejection;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class BrandRejectionReasonAddedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2490922833408695873L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BrandRejectionReasonAddedAvroModel\",\"namespace\":\"az.kon.academy.catalog.avro.model.brandrejection\",\"fields\":[{\"name\":\"brandId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"moderatedBy\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"reason\",\"type\":\"string\"},{\"name\":\"solved\",\"type\":\"boolean\"},{\"name\":\"aggregateId\",\"type\":\"string\"},{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"version\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<BrandRejectionReasonAddedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BrandRejectionReasonAddedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BrandRejectionReasonAddedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BrandRejectionReasonAddedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BrandRejectionReasonAddedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BrandRejectionReasonAddedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BrandRejectionReasonAddedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BrandRejectionReasonAddedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BrandRejectionReasonAddedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID brandId;
  private java.util.UUID moderatedBy;
  private java.lang.CharSequence reason;
  private boolean solved;
  private java.lang.CharSequence aggregateId;
  private java.util.UUID eventId;
  private java.time.Instant timestamp;
  private int version;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BrandRejectionReasonAddedAvroModel() {}

  /**
   * All-args constructor.
   * @param brandId The new value for brandId
   * @param moderatedBy The new value for moderatedBy
   * @param reason The new value for reason
   * @param solved The new value for solved
   * @param aggregateId The new value for aggregateId
   * @param eventId The new value for eventId
   * @param timestamp The new value for timestamp
   * @param version The new value for version
   */
  public BrandRejectionReasonAddedAvroModel(java.util.UUID brandId, java.util.UUID moderatedBy, java.lang.CharSequence reason, java.lang.Boolean solved, java.lang.CharSequence aggregateId, java.util.UUID eventId, java.time.Instant timestamp, java.lang.Integer version) {
    this.brandId = brandId;
    this.moderatedBy = moderatedBy;
    this.reason = reason;
    this.solved = solved;
    this.aggregateId = aggregateId;
    this.eventId = eventId;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.version = version;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return brandId;
    case 1: return moderatedBy;
    case 2: return reason;
    case 3: return solved;
    case 4: return aggregateId;
    case 5: return eventId;
    case 6: return timestamp;
    case 7: return version;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: brandId = (java.util.UUID)value$; break;
    case 1: moderatedBy = (java.util.UUID)value$; break;
    case 2: reason = (java.lang.CharSequence)value$; break;
    case 3: solved = (java.lang.Boolean)value$; break;
    case 4: aggregateId = (java.lang.CharSequence)value$; break;
    case 5: eventId = (java.util.UUID)value$; break;
    case 6: timestamp = (java.time.Instant)value$; break;
    case 7: version = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'brandId' field.
   * @return The value of the 'brandId' field.
   */
  public java.util.UUID getBrandId() {
    return brandId;
  }

  /**
   * Gets the value of the 'brandId' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalBrandId() {
    return Optional.<java.util.UUID>ofNullable(brandId);
  }

  /**
   * Sets the value of the 'brandId' field.
   * @param value the value to set.
   */
  public void setBrandId(java.util.UUID value) {
    this.brandId = value;
  }

  /**
   * Gets the value of the 'moderatedBy' field.
   * @return The value of the 'moderatedBy' field.
   */
  public java.util.UUID getModeratedBy() {
    return moderatedBy;
  }

  /**
   * Gets the value of the 'moderatedBy' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalModeratedBy() {
    return Optional.<java.util.UUID>ofNullable(moderatedBy);
  }

  /**
   * Sets the value of the 'moderatedBy' field.
   * @param value the value to set.
   */
  public void setModeratedBy(java.util.UUID value) {
    this.moderatedBy = value;
  }

  /**
   * Gets the value of the 'reason' field.
   * @return The value of the 'reason' field.
   */
  public java.lang.CharSequence getReason() {
    return reason;
  }

  /**
   * Gets the value of the 'reason' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalReason() {
    return Optional.<java.lang.CharSequence>ofNullable(reason);
  }

  /**
   * Sets the value of the 'reason' field.
   * @param value the value to set.
   */
  public void setReason(java.lang.CharSequence value) {
    this.reason = value;
  }

  /**
   * Gets the value of the 'solved' field.
   * @return The value of the 'solved' field.
   */
  public boolean getSolved() {
    return solved;
  }

  /**
   * Gets the value of the 'solved' field as an Optional&lt;java.lang.Boolean&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Boolean&gt;.
   */
  public Optional<java.lang.Boolean> getOptionalSolved() {
    return Optional.<java.lang.Boolean>ofNullable(solved);
  }

  /**
   * Sets the value of the 'solved' field.
   * @param value the value to set.
   */
  public void setSolved(boolean value) {
    this.solved = value;
  }

  /**
   * Gets the value of the 'aggregateId' field.
   * @return The value of the 'aggregateId' field.
   */
  public java.lang.CharSequence getAggregateId() {
    return aggregateId;
  }

  /**
   * Gets the value of the 'aggregateId' field as an Optional&lt;java.lang.CharSequence&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
   */
  public Optional<java.lang.CharSequence> getOptionalAggregateId() {
    return Optional.<java.lang.CharSequence>ofNullable(aggregateId);
  }

  /**
   * Sets the value of the 'aggregateId' field.
   * @param value the value to set.
   */
  public void setAggregateId(java.lang.CharSequence value) {
    this.aggregateId = value;
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.util.UUID getEventId() {
    return eventId;
  }

  /**
   * Gets the value of the 'eventId' field as an Optional&lt;java.util.UUID&gt;.
   * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
   */
  public Optional<java.util.UUID> getOptionalEventId() {
    return Optional.<java.util.UUID>ofNullable(eventId);
  }

  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.util.UUID value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }

  /**
   * Gets the value of the 'timestamp' field as an Optional&lt;java.time.Instant&gt;.
   * @return The value wrapped in an Optional&lt;java.time.Instant&gt;.
   */
  public Optional<java.time.Instant> getOptionalTimestamp() {
    return Optional.<java.time.Instant>ofNullable(timestamp);
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public int getVersion() {
    return version;
  }

  /**
   * Gets the value of the 'version' field as an Optional&lt;java.lang.Integer&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
   */
  public Optional<java.lang.Integer> getOptionalVersion() {
    return Optional.<java.lang.Integer>ofNullable(version);
  }

  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(int value) {
    this.version = value;
  }

  /**
   * Creates a new BrandRejectionReasonAddedAvroModel RecordBuilder.
   * @return A new BrandRejectionReasonAddedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder newBuilder() {
    return new az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder();
  }

  /**
   * Creates a new BrandRejectionReasonAddedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BrandRejectionReasonAddedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new BrandRejectionReasonAddedAvroModel RecordBuilder by copying an existing BrandRejectionReasonAddedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new BrandRejectionReasonAddedAvroModel RecordBuilder
   */
  public static az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder newBuilder(az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel other) {
    if (other == null) {
      return new az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder();
    } else {
      return new az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for BrandRejectionReasonAddedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BrandRejectionReasonAddedAvroModel>
    implements org.apache.avro.data.RecordBuilder<BrandRejectionReasonAddedAvroModel> {

    private java.util.UUID brandId;
    private java.util.UUID moderatedBy;
    private java.lang.CharSequence reason;
    private boolean solved;
    private java.lang.CharSequence aggregateId;
    private java.util.UUID eventId;
    private java.time.Instant timestamp;
    private int version;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.brandId)) {
        this.brandId = data().deepCopy(fields()[0].schema(), other.brandId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.moderatedBy)) {
        this.moderatedBy = data().deepCopy(fields()[1].schema(), other.moderatedBy);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.reason)) {
        this.reason = data().deepCopy(fields()[2].schema(), other.reason);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.solved)) {
        this.solved = data().deepCopy(fields()[3].schema(), other.solved);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[4].schema(), other.aggregateId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.eventId)) {
        this.eventId = data().deepCopy(fields()[5].schema(), other.eventId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.version)) {
        this.version = data().deepCopy(fields()[7].schema(), other.version);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing BrandRejectionReasonAddedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.brandId)) {
        this.brandId = data().deepCopy(fields()[0].schema(), other.brandId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.moderatedBy)) {
        this.moderatedBy = data().deepCopy(fields()[1].schema(), other.moderatedBy);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.reason)) {
        this.reason = data().deepCopy(fields()[2].schema(), other.reason);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.solved)) {
        this.solved = data().deepCopy(fields()[3].schema(), other.solved);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.aggregateId)) {
        this.aggregateId = data().deepCopy(fields()[4].schema(), other.aggregateId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.eventId)) {
        this.eventId = data().deepCopy(fields()[5].schema(), other.eventId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.version)) {
        this.version = data().deepCopy(fields()[7].schema(), other.version);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'brandId' field.
      * @return The value.
      */
    public java.util.UUID getBrandId() {
      return brandId;
    }

    /**
      * Gets the value of the 'brandId' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalBrandId() {
      return Optional.<java.util.UUID>ofNullable(brandId);
    }

    /**
      * Sets the value of the 'brandId' field.
      * @param value The value of 'brandId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder setBrandId(java.util.UUID value) {
      validate(fields()[0], value);
      this.brandId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'brandId' field has been set.
      * @return True if the 'brandId' field has been set, false otherwise.
      */
    public boolean hasBrandId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'brandId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder clearBrandId() {
      brandId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'moderatedBy' field.
      * @return The value.
      */
    public java.util.UUID getModeratedBy() {
      return moderatedBy;
    }

    /**
      * Gets the value of the 'moderatedBy' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalModeratedBy() {
      return Optional.<java.util.UUID>ofNullable(moderatedBy);
    }

    /**
      * Sets the value of the 'moderatedBy' field.
      * @param value The value of 'moderatedBy'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder setModeratedBy(java.util.UUID value) {
      validate(fields()[1], value);
      this.moderatedBy = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'moderatedBy' field has been set.
      * @return True if the 'moderatedBy' field has been set, false otherwise.
      */
    public boolean hasModeratedBy() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'moderatedBy' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder clearModeratedBy() {
      moderatedBy = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'reason' field.
      * @return The value.
      */
    public java.lang.CharSequence getReason() {
      return reason;
    }

    /**
      * Gets the value of the 'reason' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalReason() {
      return Optional.<java.lang.CharSequence>ofNullable(reason);
    }

    /**
      * Sets the value of the 'reason' field.
      * @param value The value of 'reason'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder setReason(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.reason = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'reason' field has been set.
      * @return True if the 'reason' field has been set, false otherwise.
      */
    public boolean hasReason() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'reason' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder clearReason() {
      reason = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'solved' field.
      * @return The value.
      */
    public boolean getSolved() {
      return solved;
    }

    /**
      * Gets the value of the 'solved' field as an Optional&lt;java.lang.Boolean&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Boolean&gt;.
      */
    public Optional<java.lang.Boolean> getOptionalSolved() {
      return Optional.<java.lang.Boolean>ofNullable(solved);
    }

    /**
      * Sets the value of the 'solved' field.
      * @param value The value of 'solved'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder setSolved(boolean value) {
      validate(fields()[3], value);
      this.solved = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'solved' field has been set.
      * @return True if the 'solved' field has been set, false otherwise.
      */
    public boolean hasSolved() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'solved' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder clearSolved() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'aggregateId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAggregateId() {
      return aggregateId;
    }

    /**
      * Gets the value of the 'aggregateId' field as an Optional&lt;java.lang.CharSequence&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
      */
    public Optional<java.lang.CharSequence> getOptionalAggregateId() {
      return Optional.<java.lang.CharSequence>ofNullable(aggregateId);
    }

    /**
      * Sets the value of the 'aggregateId' field.
      * @param value The value of 'aggregateId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder setAggregateId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.aggregateId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'aggregateId' field has been set.
      * @return True if the 'aggregateId' field has been set, false otherwise.
      */
    public boolean hasAggregateId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'aggregateId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder clearAggregateId() {
      aggregateId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.util.UUID getEventId() {
      return eventId;
    }

    /**
      * Gets the value of the 'eventId' field as an Optional&lt;java.util.UUID&gt;.
      * @return The value wrapped in an Optional&lt;java.util.UUID&gt;.
      */
    public Optional<java.util.UUID> getOptionalEventId() {
      return Optional.<java.util.UUID>ofNullable(eventId);
    }

    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder setEventId(java.util.UUID value) {
      validate(fields()[5], value);
      this.eventId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }

    /**
      * Gets the value of the 'timestamp' field as an Optional&lt;java.time.Instant&gt;.
      * @return The value wrapped in an Optional&lt;java.time.Instant&gt;.
      */
    public Optional<java.time.Instant> getOptionalTimestamp() {
      return Optional.<java.time.Instant>ofNullable(timestamp);
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[6], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder clearTimestamp() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public int getVersion() {
      return version;
    }

    /**
      * Gets the value of the 'version' field as an Optional&lt;java.lang.Integer&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
      */
    public Optional<java.lang.Integer> getOptionalVersion() {
      return Optional.<java.lang.Integer>ofNullable(version);
    }

    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder setVersion(int value) {
      validate(fields()[7], value);
      this.version = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public az.kon.academy.catalog.avro.model.brandrejection.BrandRejectionReasonAddedAvroModel.Builder clearVersion() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BrandRejectionReasonAddedAvroModel build() {
      try {
        BrandRejectionReasonAddedAvroModel record = new BrandRejectionReasonAddedAvroModel();
        record.brandId = fieldSetFlags()[0] ? this.brandId : (java.util.UUID) defaultValue(fields()[0]);
        record.moderatedBy = fieldSetFlags()[1] ? this.moderatedBy : (java.util.UUID) defaultValue(fields()[1]);
        record.reason = fieldSetFlags()[2] ? this.reason : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.solved = fieldSetFlags()[3] ? this.solved : (java.lang.Boolean) defaultValue(fields()[3]);
        record.aggregateId = fieldSetFlags()[4] ? this.aggregateId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.eventId = fieldSetFlags()[5] ? this.eventId : (java.util.UUID) defaultValue(fields()[5]);
        record.timestamp = fieldSetFlags()[6] ? this.timestamp : (java.time.Instant) defaultValue(fields()[6]);
        record.version = fieldSetFlags()[7] ? this.version : (java.lang.Integer) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BrandRejectionReasonAddedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<BrandRejectionReasonAddedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BrandRejectionReasonAddedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<BrandRejectionReasonAddedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }


  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (brandId == null ? 0 : brandId.hashCode());
    result = 31 * result + (moderatedBy == null ? 0 : moderatedBy.hashCode());
    result = 31 * result + (reason == null ? 0 : reason.hashCode());
    result = 31 * result + Boolean.hashCode(solved);
    result = 31 * result + (aggregateId == null ? 0 : aggregateId.hashCode());
    result = 31 * result + (eventId == null ? 0 : eventId.hashCode());
    result = 31 * result + (timestamp == null ? 0 : timestamp.hashCode());
    result = 31 * result + Integer.hashCode(version);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof BrandRejectionReasonAddedAvroModel)) {
      return false;
    }
    BrandRejectionReasonAddedAvroModel other = (BrandRejectionReasonAddedAvroModel) o;
    if (!java.util.Objects.equals(this.brandId, other.brandId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.moderatedBy, other.moderatedBy)) {
      return false;
    }
    if (Utf8.compareSequences(this.reason, other.reason) != 0) {
      return false;
    }
    if (this.solved != other.solved) {
      return false;
    }
    if (Utf8.compareSequences(this.aggregateId, other.aggregateId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.eventId, other.eventId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.timestamp, other.timestamp)) {
      return false;
    }
    if (this.version != other.version) {
      return false;
    }
    return true;
  }
}










