package az.kon.academy.catalog.command.service.application.service.constant;

public interface SecurityPermissions {
    interface Role {
        String ROLE_SYSTEM              = "system";
        String ROLE_CUSTOMER            = "customer";
        String ROLE_MERCHANT            = "merchant";
        String ROLE_DOMAIN_MODERATOR    = "moderator";
    }

    interface Brand {
        String BRAND_MANAGEMENT_CREATE                              = "BRAND_MANAGEMENT_CREATE";
        String BRAND_MANAGEMENT_CHANGE_INFORMATION                  = "BRAND_MANAGEMENT_CHANGE_INFORMATION";
        String BRAND_MANAGEMENT_CHANGE_IMAGE                        = "BRAND_MANAGEMENT_CHANGE_IMAGE";
        String BRAND_MANAGEMENT_MOVE_DRAFT                          = "BRAND_MANAGEMENT_MOVE_DRAFT";
        String BRAND_MANAGEMENT_SENT_TO_APPROVAL                    = "BRAND_MANAGEMENT_SENT_TO_APPROVAL";
        String BRAND_MANAGEMENT_SOLVE_REJECT_REASON                 = "BRAND_MANAGEMENT_SOLVE_REJECT_REASON";

        String BRAND_MODERATION_CREATE                              = "BRAND_MODERATION_CREATE";
        String BRAND_MODERATION_CHANGE_INFORMATION                  = "BRAND_MODERATION_CHANGE_INFORMATION";
        String BRAND_MODERATION_CHANGE_IMAGE                        = "BRAND_MODERATION_CHANGE_IMAGE";
        String BRAND_MODERATION_APPROVE                             = "BRAND_MODERATION_APPROVE";
        String BRAND_MODERATION_REJECT                              = "BRAND_MODERATION_REJECT";
        String BRAND_MODERATION_CHANGE_OWNER                        = "BRAND_MODERATION_CHANGE_OWNER";
        String BRAND_MODERATION_CHANGE_GLOBAL                       = "BRAND_MODERATION_CHANGE_GLOBAL";
        String BRAND_MODERATION_MARK_IN_REVIEW                      = "BRAND_MODERATION_MARK_IN_REVIEW";
        String BRAND_MODERATION_ADD_REJECTION_REASON                = "BRAND_MODERATION_ADD_REJECTION_REASON";
        String BRAND_MODERATION_CHANGE_REJECTION_REASON             = "BRAND_MODERATION_CHANGE_REJECTION_REASON";
        String BRAND_MODERATION_REMOVE_REJECTION_REASON             = "BRAND_MODERATION_REMOVE_REJECTION_REASON";
    }

    interface ProductCategory {
        String PRODUCT_CATEGORY_MODERATION_CREATE                   = "PRODUCT_CATEGORY_CREATE";
        String PRODUCT_CATEGORY_MODERATION_ACTIVATE                 = "PRODUCT_CATEGORY_ACTIVATE";
        String PRODUCT_CATEGORY_MODERATION_ARCHIVE                  = "PRODUCT_CATEGORY_ARCHIVE";
        String PRODUCT_CATEGORY_MODERATION_DELETE                   = "PRODUCT_CATEGORY_ARCHIVE";
        String PRODUCT_CATEGORY_MODERATION_CHANGE_IMAGE             = "PRODUCT_CATEGORY_CHANGE_IMAGE";
        String PRODUCT_CATEGORY_MODERATION_CHANGE_INFORMATION       = "PRODUCT_CATEGORY_CHANGE_INFORMATION";
        String PRODUCT_CATEGORY_MODERATION_CHANGE_PARENT            = "PRODUCT_CATEGORY_CHANGE_PARENT";
    }

    interface ProductSpecification {
        String PRODUCT_SPECIFICATION_MODERATION_ASSIGN_CATEGORY = "PRODUCT_SPECIFICATION_ASSIGN_CATEGORY";
        String PRODUCT_SPECIFICATION_MODERATION_CHANGE_INFORMATION = "PRODUCT_SPECIFICATION_CHANGE_INFORMATION";
        String PRODUCT_SPECIFICATION_MODERATION_CREATE = "PRODUCT_SPECIFICATION_CREATE";
        String PRODUCT_SPECIFICATION_MODERATION_DELETE = "PRODUCT_SPECIFICATION_DELETE";
        String PRODUCT_SPECIFICATION_MODERATION_REMOVE_CATEGORY_ASSIGNMENT = "PRODUCT_SPECIFICATION_REMOVE_CATEGORY_ASSIGNMENT";
    }

    interface Product {
        String PRODUCT_CREATE                   = "PRODUCT_CREATE";
        String PRODUCT_CHANGE_INFORMATION       = "PRODUCT_CHANGE_INFORMATION";
        String PRODUCT_ARCHIVE                  = "PRODUCT_ARCHIVE";
        String PRODUCT_ASSIGN_BRAND             = "PRODUCT_ASSIGN_BRAND";
        String PRODUCT_ASSIGN_CATEGORY          = "PRODUCT_ASSIGN_CATEGORY";
        String PRODUCT_ASSIGN_SPECIFICATION     = "PRODUCT_ASSIGN_SPECIFICATION";
        String PRODUCT_REMOVE_SPECIFICATION     = "PRODUCT_REMOVE_SPECIFICATION";
        String PRODUCT_ADD_VARIANT              = "PRODUCT_ADD_VARIANT";
        String PRODUCT_REMOVE_VARIANT           = "PRODUCT_REMOVE_VARIANT";
        String PRODUCT_CREATE_REJECTION_REASON  = "PRODUCT_CREATE_REJECTION_REASON";
        String PRODUCT_PRICE_CREATE             = "PRODUCT_PRICE_CREATE";
        String PRODUCT_PRICE_UPDATE             = "PRODUCT_PRICE_UPDATE";
        String PRODUCT_STOCK_CREATE             = "PRODUCT_STOCK_CREATE";
        String PRODUCT_STOCK_INCREASE           = "PRODUCT_STOCK_INCREASE";
        String PRODUCT_STOCK_DECREASE           = "PRODUCT_STOCK_DECREASE";
    }

    interface Variant {
        String VARIANT_KEY_CREATE               = "VARIANT_KEY_CREATE";
        String VARIANT_KEY_CHANGE_NAME          = "VARIANT_KEY_CHANGE_NAME";
        String VARIANT_KEY_CHANGE_DESCRIPTION   = "VARIANT_KEY_CHANGE_DESCRIPTION";
        String VARIANT_VALUE_CREATE             = "VARIANT_VALUE_CREATE";
        String VARIANT_VALUE_CHANGE_NAME        = "VARIANT_VALUE_CHANGE_NAME";
    }
}
